#Get data from canard site DONE
#convert data from json into Excel file DONE
#compare the data to other data in the same format (different row amount) DONE
#comparison takes place for lat, lon rounded to third decimal point DONE
import os
import requests
import datetime
import csv
import pandas as pd

#Get data from canard site
x = requests.post('https://www.canard.gitd.gov.pl/canard-cms-dodatki-rest/fotoradary/pobierzPP')

#Convert into JSON (though I thought it was already in JSON?)
fix_list = x.json()
#date for naming purposes
curr_date = datetime.datetime.now()

#when loading older file not generated by this program, make sure the data is compatible
old_file_name = input('Write a name of the file you want to compare new data with: ')

#write the data into excel file
with open(f'CANARD_FIX_{curr_date.month}-{curr_date.year}.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    header = ['ID', 'Lon', 'Lat', 'nrSeryjny']
    writer.writerow(header)
    for record in fix_list:
        row = [record['id'],round(record['lon'], 3),round(record['lat'], 3),record['nrSeryjny']]
        writer.writerow(row)


#Comparing excel files
old_version = os.path.join(os.getcwd(), f'{old_file_name}')
new_version = os.path.join(os.getcwd(), f'CANARD_FIX_{curr_date.month}-{curr_date.year}.csv')

df_old = pd.read_csv(old_version)
df_new = pd.read_csv(new_version)


df_difference = pd.merge(df_old, df_new, how='outer', indicator='Exists')
df_highlight = df_difference.query("Exists != 'both'")

#to avoid duplicates when doing both
df_highlight = df_highlight.drop_duplicates(subset='ID', keep=False)
#removing older values after filtering out duplicates
df_highlight = df_highlight[df_highlight.Exists == 'right_only']
#Only those headers will be in result file
result_header = ["ID", "nrSeryjny", "Lat", "Lon", "Exists"]
df_highlight = df_highlight.reindex(columns=result_header)
#Save result file
df_highlight.to_csv(f'Result_files/CANARD_FIX_{curr_date.month}-{curr_date.year}-results.csv')
